host.base.url: http://ec2-3-95-178-58.compute-1.amazonaws.com:3030
#host.base.url: http://localhost:3030

server:
  port: 3030
  servlet.session.cookie:
    name: onlinestore
    path: /
    httpOnly: true
    secure: false

#spring.jpa.hibernate.ddl-auto=update
spring:
  application:
    name: OnlineStore
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://onlinestore-db:5432/store_db?user=store_user&password=123456&serverTimezone=UTC&useSSL=false
    username: store_user
    password: 123456
    hikari:
      auto-commit: false
      maximum-pool-size: 1
  liquibase:
    change-log: classpath:db/changelog.xml
  security:
    user:
      password: password
      name: user
  banner: banner.txt
  sql:
    init:
      mode: always
      platform: org.hibernate.dialect.PostgreSQLDialect
