version: "3.3"

services:
  onlinestore-app:
    image: 'online-store-image'
    build:
      context: ..
    container_name: onlinestore_app
    ports:
      - "3030:8080"
    expose:
      - 3030
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://onlinestore-db:5432/store_db?user=store_user&password=123456&serverTimezone=UTC&useSSL=false
      - SPRING_DATASOURCE_USERNAME=store_user
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - online-store-network
networks:
  online-store-network:
