version: "3.3"

volumes:
  postgres-onlinestore-data:

services:
  onlinestore-db:
    image: postgres:11-alpine
    container_name: store_db
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=store_user
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-onlinestore-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - online-store-network
networks:
  online-store-network: