version: "3.9"

services:
  onlinestore-app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ..
    container_name: onlinestore_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://onlinestore-db:5432/store_db?user=store_user&password=123456&serverTimezone=UTC&useSSL=false
      - SPRING_DATASOURCE_USERNAME=store_user
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
